version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "123_password"
    volumes:
      - .db_data:/var/lib/mysql
    ports:
      - "3306:3306"
